package com.starkindustries.radientdermat.Utility

import androidx.compose.foundation.Image
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Camera
import androidx.compose.material.icons.filled.Home
import androidx.compose.material.icons.filled.Person
import androidx.compose.material.icons.outlined.Camera
import androidx.compose.material.icons.outlined.Home
import androidx.compose.material.icons.outlined.Person
import androidx.compose.material3.Icon
import androidx.compose.runtime.Composable
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.res.painterResource
import com.starkindustries.radientdermat.Data.TabItem
import com.starkindustries.radientdermat.Frontend.Screens.Patient.Data.DiseasesTab
import com.starkindustries.radientdermat.R

class Utility{
    companion object{
        fun getTabItemList():List<TabItem>{

            var list = listOf(
                TabItem(title = "Home", selectedIcon = Icons.Filled.Home, unSelectedIcon = Icons.Outlined.Home)
                , TabItem(title = "Capture", selectedIcon = Icons.Filled.Camera, unSelectedIcon = Icons.Outlined.Camera)
                , TabItem(title = "Profile", selectedIcon = Icons.Filled.Person, unSelectedIcon = Icons.Outlined.Person)
            )
            return list
        }

        @Composable
        fun getDiseasesTab():List<DiseasesTab>{
            return listOf(
                DiseasesTab(0,"Acne", painter = painterResource(id = R.drawable.acne)
                    , symtom = "Acne is a skin condition affecting areas like the face, chest, and back, characterized by blackheads, whiteheads, papules, pustules, nodules, and cysts. Symptoms include redness, swelling, oiliness, and uneven skin texture, with severe cases potentially causing scarring. Treatment is crucial to manage symptoms and prevent complications."
                    , remedy = " Acne treatment depends on its severity and includes topical creams like benzoyl peroxide, salicylic acid, or retinoids for mild cases, and oral antibiotics, hormonal therapy, or isotretinoin for severe cases. A gentle skincare routine, stress management, and a healthy diet can support treatment. For persistent or scarring acne, dermatological procedures like chemical peels or laser therapy may be effective. Early intervention is key to preventing complications and improving skin health.", isSelected = false),
                DiseasesTab(1,"Rashes", painter = painterResource(id = R.drawable.reshes), symtom = "Rashes are characterized by changes in the skin's appearance, texture, or color. Symptoms include redness, swelling, itching, and irritation. The affected area may develop bumps, blisters, or scaly patches, and in some cases, the skin may feel warm or tender. Rashes can appear on a specific part of the body or spread across larger areas, often resulting from allergic reactions, infections, heat, or skin conditions like eczema or psoriasis. Severe cases may include oozing, pain, or fever, requiring medical attention."
                    , remedy = "The treatment for rashes depends on the underlying cause. For mild cases, soothing the skin with cool compresses, moisturizers, or over-the-counter creams containing hydrocortisone can help reduce itching and inflammation. Antihistamines may be used to manage allergic reactions, while antifungal or antibacterial medications are necessary for infections. Avoiding irritants, allergens, and excessive heat can prevent worsening of the rash. In more severe cases, such as those caused by eczema, psoriasis, or other chronic conditions, prescription medications like topical steroids, immunomodulators, or systemic treatments may be needed. If the rash is accompanied by severe symptoms like fever, pain, or oozing, medical attention is essential to address the cause and prevent complications.", isSelected = false),
                DiseasesTab(2,"Hive", painter = painterResource(id = R.drawable.hive), symtom = "Hives (urticaria) are characterized by red, raised, itchy welts on the skin. These welts can vary in size, shape, and location, and may appear and disappear quickly or persist for hours to days. Symptoms include intense itching, swelling, and a burning or stinging sensation. The welts often turn white when pressed and may merge to form larger patches. In severe cases, hives can be accompanied by swelling of the lips, tongue, or throat (angioedema), which can interfere with breathing and requires immediate medical attention. Hives are often triggered by allergens, infections, stress, medications, or environmental factors."
                    , remedy = "The treatment for hives focuses on relieving symptoms and addressing the underlying cause. For mild cases, over-the-counter antihistamines (such as loratadine or cetirizine) can help reduce itching and swelling. For more severe or persistent hives, doctors may prescribe stronger antihistamines or corticosteroids to reduce inflammation. Avoiding known triggers, such as certain foods, medications, or allergens, is key in preventing outbreaks. In cases of angioedema (swelling in deeper layers of the skin), epinephrine may be needed if there is difficulty breathing. For chronic hives, additional treatments like leukotriene inhibitors or immunosuppressants may be considered. If the hives are linked to an underlying health condition, addressing that condition is essential for long-term relief.", isSelected = false),
                DiseasesTab(3,"Eczema", painter = painterResource(id = R.drawable.eczema), symtom = "Eczema (atopic dermatitis) is a chronic skin condition that causes inflammation, redness, and irritation. Common symptoms include dry, itchy skin, redness, and rashes that may appear in patches. The skin can become thickened, cracked, or scaly, and there may be fluid-filled blisters that can ooze and crust over. Eczema often affects the face, hands, feet, or behind the knees, and the severity of the symptoms can vary. Scratching may worsen the condition, leading to further irritation or infection. In some cases, eczema can also cause discomfort, burning, or stinging sensations."
                    , remedy = "Alternative remedies for eczema include using coconut oil for moisturizing and reducing inflammation, aloe vera gel to soothe irritated skin, and colloidal oatmeal baths to calm itching. Honey can help with its antibacterial properties, while diluted tea tree oil may reduce skin irritation. Probiotics might support the immune system, and chamomile tea compresses can alleviate redness. Additionally, turmeric’s anti-inflammatory properties may reduce flare-ups. Always consult a healthcare provider before trying alternative treatments to ensure they’re safe and effective for your skin.", isSelected = false),
                DiseasesTab(4,"Vitiligo", painter = painterResource(id = R.drawable.vitiligo), symtom = "Vitiligo is a highly contagious viral infection that primarily affects children, with symptoms appearing 10 to 14 days after exposure. It typically begins with a high fever, dry cough, runny nose, and red, watery eyes. Sensitivity to light and swollen eyelids may also occur, along with white spots called Koplik spots inside the mouth, which often appear before the rash. A red, blotchy rash usually starts on the face, behind the ears, and spreads downward to the neck, torso, arms, and legs. As the rash progresses, the fever tends to worsen. Measles can lead to serious complications, including pneumonia, encephalitis, and even death, especially in young children or those with weakened immune systems. Vaccination is the most effective way to prevent measles."
                    , remedy = "There is no specific cure for Vitiligo, but treatment focuses on relieving symptoms and managing complications. The primary approach includes rest, hydration, and over-the-counter medications like acetaminophen or ibuprofen to reduce fever and relieve pain. Antibiotics may be prescribed if a secondary bacterial infection, such as pneumonia, develops. Vitamin A supplementation is recommended for children with measles, as it can reduce the risk of complications and improve recovery. For more severe cases, hospitalization may be required for supportive care, including fluids and treatment for complications. Measles can be prevented with the MMR vaccine, which is highly effective at protecting against the virus.", isSelected = false),
                DiseasesTab(5,"Measles", painter = painterResource(id = R.drawable.vitiligo), symtom = "Measles is a skin condition where patches of skin lose their pigmentation, resulting in lighter or white spots. The main symptom is the appearance of these depigmented areas, which can develop anywhere on the body but are commonly found on the face, hands, arms, and genitals. The size and shape of the patches can vary, and they may spread over time. In some cases, the hair in the affected areas may turn white or gray. Vitiligo can also cause the skin to become more sensitive to the sun in areas where pigment is lost. The condition is generally painless and does not cause physical discomfort, but it can have emotional and psychological effects due to changes in appearance."
                    , remedy = "There is no specific cure for measles, but treatment focuses on relieving symptoms and managing complications. The primary approach includes rest, hydration, and over-the-counter medications like acetaminophen or ibuprofen to reduce fever and relieve pain. Antibiotics may be prescribed if a secondary bacterial infection, such as pneumonia, develops. Vitamin A supplementation is recommended for children with measles, as it can reduce the risk of complications and improve recovery. For more severe cases, hospitalization may be required for supportive care, including fluids and treatment for complications. Measles can be prevented with the MMR vaccine, which is highly effective at protecting against the virus.", isSelected = false),
                DiseasesTab(6,"Shingles", painter = painterResource(id = R.drawable.shingles), symtom = "Shingles (herpes zoster) is a viral infection caused by the reactivation of the varicella-zoster virus, which also causes chickenpox. The primary symptoms include pain or a tingling sensation in a specific area of the body, often preceding the rash. A red rash appears a few days later, typically on one side of the chest, back, or face, followed by blisters that may ooze and crust over. The affected area can be intensely itchy, and individuals may experience additional symptoms such as fever, fatigue, headache, or sensitivity to light. While the rash generally heals within 2–4 weeks, some people may experience lingering pain, known as postherpetic neuralgia, long after the rash has resolved."
                    , remedy = "Shingles treatment focuses on relieving pain, speeding up healing, and preventing complications. Antiviral medications like acyclovir, valacyclovir, or famciclovir are commonly prescribed to reduce the severity and duration of the infection if started within 72 hours of the rash appearing. Pain relievers such as ibuprofen or acetaminophen can help manage discomfort. For more severe pain, doctors may recommend stronger painkillers, topical creams, or nerve blocks. In some cases, corticosteroids may be prescribed to reduce inflammation. Keeping the rash clean and dry can help prevent infection. For those with postherpetic neuralgia, medications like gabapentin or tricyclic antidepressants may be used to manage lingering pain. Vaccination, such as the shingles vaccine (Shingrix), can help reduce the risk of developing shingles or minimize the severity if it occurs.", isSelected = false)
            )
        }

    }
}

